---
- name: Configure firewalld
  when: >
    'services' in ansible_facts and
    'firewalld.service' in ansible_facts.services and
    ansible_facts.services['firewalld.service'].state == 'running'
  become: true
  block:
    - name: open boundary-controller tcp port
      when: group_names is search('boundary_controllers')
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - 9200

    - name: open boundary-worker tcp port
      when: group_names is search('boundary_workers')
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - 9202

- name: Configure ufw firewall
  when: >
    'services' in ansible_facts and
    'ufw.service' in ansible_facts.services and
    ansible_facts.services['ufw.service'].state == 'running'
  become: true
  block:
    - name: open boundary-controller tcp port
      when: group_names is search('boundary_controllers')
      community.general.ufw:
        name: Boundary Controller API
        state: enabled
        rule: limit
        to_port: "{{ item }}"
        proto: tcp
      with_items:
        - 9200

    - name: open boundary-worker tcp port
      when: group_names is search('boundary_workers')
      community.general.ufw:
        name: Boundary Worker API
        state: enabled
        rule: limit
        to_port: "{{ item }}"
        proto: tcp
      with_items:
        - 9202
